### ISSUE TITLE
TypeError: Cannot read property "snippet" from undefined. (line 46, file "Code")

### ISSUE THREAD

**Issue by MichaelBatistich** [aliciawilliams/youtube-tracker#1]
Hi Alicia,

I am getting errors when I run the scripts. Occasionally I am getting around 10 rows of results but no more. I have tried using different email accounts but no joy.

I Googled the error and was wondering if I need to load a javascript library as mentioned in this post on Stackoverflow.

https://stackoverflow.com/questions/46175399/typeerror-cannot-read-property-snippet-of-undefined

I would be grateful if you could share any thoughts on how I could resolve the issue?

Thanks in advance

**Comment by aliciawilliams** [comment]
What is the format of the YouTube URLs? The logic is only built to handle certain versions.

**Comment by Kubwayojc** [comment]
Hi Michael and Alicia, 

I am experiencing the same problem. It only started today. I have been using this script for the last two months without any issues. Let me know if there is a way around it.

Thanks.

**Comment by aliciawilliams** [comment]
The code is very restrictive on the type of YouTube URL it will accept. Please make sure your URL starts with the format: https://www.youtube.com/watch?v=

Please reply if that does not solve the issue.
