### ISSUE TITLE
TypeError: Cannot call method "split" of undefined. (line 90, file "Code")

### ISSUE THREAD

**Issue by hashimaziz1** [aliciawilliams/youtube-tracker#3]
Firstly, thanks for the great project, it's exactly what I needed, although the documentation should probably be updated to reflect the new editor as I had to switch to the legacy one to follow it (thankfully that's still an option, but probably won't be for long).

I have one URL in cell A2 but when I run the script I get the error:

```
TypeError: Cannot call method "split" of undefined. (line 90, file "Code")
```

...and no details are pulled into the spreadsheet.

**Comment by aliciawilliams** [comment]
Hi, I'm glad it's useful! The code is very restrictive on the type of YouTube URL it will accept. Please make sure your URL starts with the format: https://www.youtube.com/watch?v=

Try this and let me know if it works!

I've also updated the README to account for the new editor, so hopefully those setup steps are clearer.
