### ISSUE TITLE
API call to youtube.videos.list failed with error: No filter selected. Expected one of: chart, id, myRating

### ISSUE THREAD

**Issue by cimenta** [aliciawilliams/youtube-tracker#4]
I am getting this error

API call to youtube.videos.list failed with error: No filter selected. Expected one of: chart, id, myRating

**Comment by aliciawilliams** [comment]
The code from lines 78 to 83 is what calls this method, and it does provide an ID. My guess is that your video URL in column A is not in the format starting with: https://www.youtube.com/watch?v=

The logic in the code is simple and so the video URLs must be in this format. Give it a try and hopefully this solves your problem!
