### ISSUE TITLE
Change Publish Date to local time

### ISSUE THREAD

**Issue by plusteamvn** [aliciawilliams/youtube-tracker#5]
Hi, so I tried with my video and it worked.
However, the published time is 16 hours later than my local time, which I think is in PDT.
So, how can I change it to KST?

**Comment by aliciawilliams** [comment]
Hi- you can change this easily by updating the spreadsheet settings: https://support.google.com/docs/answer/58515#zippy=%2Cchange-locale-and-time-zone

After you update the settings, manually run `markVideos` from the Apps Script editor, and you will see all the times update in your spreadsheet.
